#!/usr/bin/perl
# 重復しているコードと字を検出するスクリプトです
# コードファイル（復数可）を引数として渡す

use autodie qw(open);
use strict;
use utf8;
use warnings;

binmode STDOUT, ':utf8';

my @codes_files = @ARGV;

my %all_codes;
my %all_chars;

for my $codes_file (@codes_files) {
    open my $codes, '<', $codes_file
        or die "Could not open: $!";
    binmode $codes, ':utf8';

    while (my $code_line = <$codes>) {
        chomp $code_line;
        $code_line =~ m/^([^\t]+)\t(.*)$/
            or die 'Cannot process line';
        my ($code, $character) = ($1, $2);

        my $codes_ref = $all_codes{$character} //= [];
        push @$codes_ref, $code;

        my $chars_ref = $all_chars{$code} //= [];
        push @$chars_ref, $character
    }
}

for my $character (sort keys %all_codes) {
    my $codes_ref = $all_codes{$character};
    if (@$codes_ref > 1) {
        local $/ = q{ };
        print "$character @$codes_ref\n";
    }
}

for my $code (sort keys %all_chars) {
    my $chars_ref = $all_chars{$code};
    if (@$chars_ref > 1) {
        local $/ = q{ };
        print "$code @$chars_ref\n";
    }
}
